InflationTracker/Models/ErrorViewModel.cs
namespace InflationTracker.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InflationTracker/Models/Grocery.cs
using System.ComponentModel.DataAnnotations;

namespace InflationTracker.Models
{
    public class Grocery
    {
        public int Id { get; set; }
        public CategNames category { get; set; }
        public SMNameType smname { get; set; }
        public String groceryName { get; set; }

        [Required(ErrorMessage = "Enter the issued date.")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime IssueDate { get; set; }
        public int price { get; set; }
        public Grocery()
        {

        }  
    }

    public enum CategNames { Meat, Veggies, Fruits, FlourBased, Other };
    public enum SMNameType { Mercadona, Lidl, Aldi, Bonpreu, Consum, Caprabo, Carrefour, Dia };
}

InflationTracker/Controllers/GroceriesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InflationTracker.Data;
using InflationTracker.Models;

namespace InflationTracker.Controllers
{
    public class GroceriesController : Controller
    {
        private readonly InflationTrackerContext _context;

        public GroceriesController(InflationTrackerContext context)
        {
            _context = context;
        }

        // GET: Groceries
        public async Task<IActionResult> Index()
        {
            return View(await _context.Grocery.ToListAsync());
        }

        // GET: Groceries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grocery = await _context.Grocery
                .FirstOrDefaultAsync(m => m.Id == id);
            if (grocery == null)
            {
                return NotFound();
            }

            return View(grocery);
        }

        // GET: Groceries/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Groceries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,category,smname,groceryName,IssueDate,price")] Grocery grocery)
        {
            if (ModelState.IsValid)
            {
                _context.Add(grocery);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(grocery);
        }

        // GET: Groceries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grocery = await _context.Grocery.FindAsync(id);
            if (grocery == null)
            {
                return NotFound();
            }
            return View(grocery);
        }

        // POST: Groceries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,category,smname,groceryName,IssueDate,price")] Grocery grocery)
        {
            if (id != grocery.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(grocery);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroceryExists(grocery.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(grocery);
        }

        // GET: Groceries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grocery = await _context.Grocery
                .FirstOrDefaultAsync(m => m.Id == id);
            if (grocery == null)
            {
                return NotFound();
            }

            return View(grocery);
        }

        // POST: Groceries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var grocery = await _context.Grocery.FindAsync(id);
            _context.Grocery.Remove(grocery);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GroceryExists(int id)
        {
            return _context.Grocery.Any(e => e.Id == id);
        }
    }
}

InflationTracker/Controllers/HomeController.cs
using InflationTracker.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace InflationTracker.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

InflationTracker/Views/Groceries/Create.cshtml
@model InflationTracker.Models.Grocery

@{
    ViewData["Title"] = "Create";
}

@section Scriptsee {

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script>
        $("#inflationItemSubmitButton").click(function(e) {
            if($("#inflationItemDate").val().substring(0,7) != "2022-09"){
                alert("please only choose august 2022");
                e.preventDefault();
                $("#inflationItemSubmitButton").attr('onclick', '').unbind('click');

            };
            
        })
    </script>

}

<h1>Create</h1>

<h4>Grocery</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="category" class="control-label"></label>
                <select asp-for="category" class="form-control">
                    <option value="Meat">Meat</option>
                    <option value="Veggies">Veggies</option>
                    <option value="Fruits">Fruits</option>
                    <option value="FlourBased">Flour/Flour-based</option>
                    <option value="Other">Other</option>
                </select>
                <span asp-validation-for="category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="smname" class="control-label"></label>
                <select asp-for="smname" class="form-control">
                    <option value="Mercadona">Mercadona</option>
                    <option value="Lidl">Lidl</option>
                    <option value="Aldi">Aldi</option>
                    <option value="Bonpreu">Bonpreu</option>
                    <option value="Consum">Consum</option>
                    <option value="Caprabo">Caprabo</option>
                    <option value="Carrefour">Carrefour</option>
                    <option value="Dia">Dia</option>
                </select>
                <span asp-validation-for="smname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="groceryName" class="control-label"></label>
                <select asp-for="groceryName" class="form-control">
                    <option value="cerdo">cerdo</option>
                    <option value="ternera">ternera</option>
                </select>
                <span asp-validation-for="groceryName" class="text-danger"></span>

            </div>
            <div class="form-group" id="inflationItemDateParent">
                <label asp-for="IssueDate" class="control-label"></label>
                <input asp-for="IssueDate" type="date" value=@DateTime.Today.ToString("yyyy-MM-dd") class="form-control" id="inflationItemDate" />
                <span asp-validation-for="IssueDate" class="text-danger"></span>
                <span id="clickme"> click </span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" id="inflationItemSubmitButton"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InflationTracker/Views/Groceries/Delete.cshtml
@model InflationTracker.Models.Grocery

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Grocery</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.smname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.smname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.groceryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.groceryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IssueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IssueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InflationTracker/Views/Groceries/Details.cshtml
@model InflationTracker.Models.Grocery

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Grocery</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.smname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.smname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.groceryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.groceryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IssueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IssueDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

InflationTracker/Views/Groceries/Edit.cshtml
@model InflationTracker.Models.Grocery

@{
    ViewData["Title"] = "Edit";

}

<script type="text/javascript">
        console.log( @Html.DisplayNameFor(model => model.smname) );

</script>
<h1>Edit</h1>

<h4>Grocery</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="category" class="control-label"></label>
                <select asp-for="category" class="form-control">
                    <option value="Meat">Meat</option>
                    <option value="Veggies">Veggies</option>
                    <option value="Fruits">Fruits</option>
                    <option value="FlourBased">Flour/Flour-based</option>
                    <option value="Other">Other</option>
                </select>
                <span asp-validation-for="category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="smname" class="control-label"></label>
                <select asp-for="smname" class="form-control">
                    <option value="Mercadona">Mercadona</option>
                    <option value="Lidl">Lidl</option>
                    <option value="Aldi">Aldi</option>
                    <option value="Bonpreu">Bonpreu</option>
                    <option value="Consum">Consum</option>
                    <option value="Caprabo">Caprabo</option>
                    <option value="Carrefour">Carrefour</option>
                    <option value="Dia">Dia</option>
                </select>
                <span asp-validation-for="smname" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="groceryName" class="control-label"></label>
                <input asp-for="groceryName" class="form-control" />
                <span asp-validation-for="groceryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IssueDate" class="control-label"></label>
                <input asp-for="IssueDate" type="date"  class="form-control" />
                <span asp-validation-for="IssueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="price" class="control-label"></label>
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InflationTracker/Views/Groceries/Index.cshtml
@model IEnumerable<InflationTracker.Models.Grocery>

@{
    ViewData["Title"] = "Index";
}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
  
  //filteredModelJson = [['Grocery','Price']];        

  var filteredModelJson = [];
  filteredModelJson.push(["date", "cerdo", "ternera"]);
  for(let i = 1; i<31;i++) filteredModelJson.push([i, 0, 0]);
  var rawJsonGroceries = @Html.Raw(Json.Serialize(Model));
  for(let i = 0; i < rawJsonGroceries.length; i++){
      var dateInQuestion = rawJsonGroceries[i].issueDate.substring(8,10);
      console.log("asdas " + dateInQuestion);
      if(dateInQuestion[0] == '0') dateInQuestion = dateInQuestion[1];
      console.log("asdas " + dateInQuestion);
      if(filteredModelJson[0][1] == rawJsonGroceries[i].groceryName) filteredModelJson[dateInQuestion][1] = rawJsonGroceries[i].price;
      else if (filteredModelJson[0][2] == rawJsonGroceries[i].groceryName) filteredModelJson[dateInQuestion][2] = rawJsonGroceries[i].price;
      console.log("============ " + filteredModelJson);
      //filteredModelJson.push([rawJsonGroceries[i].groceryName, rawJsonGroceries[i].price]);
  }
    
  google.charts.load("current", {packages:["corechart"]});
  google.charts.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = google.visualization.arrayToDataTable(filteredModelJson);
      var options = {
      title: 'Add a title here',
      curveType: 'function',
      legend: { position: 'none' },
    };

    var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  }
</script>

<h1>Index</h1>
<div id="chart_div" style="width: 900px; height: 500px;"></div>
<div id="jsonRaw"></div>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.smname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.groceryName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IssueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.smname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.groceryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IssueDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

InflationTracker/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
    <link rel="stylesheet" href="~/css/site.css"/>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<div class="card landing_banner center"> 
    <p>welcome</p>
    <h1>inflation shown in another light</h1>
    <p>lorem ipsum dolor sit amet</p>
</div>

<div class="row landing_firstItemsRow" >
    <div class="col-lg-4 ">
       <div class="col-lg-10 offset-lg-1 landing_item landing_firstColor" style="text-align:center">
           hellooooooooooooooooooooo    
           <svg style = "text-align:center" xmlns="http://www.w3.org/2000/svg" width="90" height="90" fill="currentColor" class="bi bi-1-circle" viewBox="0 0 16 16">
  <path d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8Zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0ZM9.283 4.002V12H7.971V5.338h-.065L6.072 6.656V5.385l1.899-1.383h1.312Z"/>
</svg>   
        </div>
    </div> 
    <div class="col-lg-4 ">
        <div class="col-lg-10 offset-lg-1 landing_item landing_secondColor" style="text-align:center">
          hellooooooooooooooooooooo    
          <svg style = "text-align:center" xmlns="http://www.w3.org/2000/svg" width="90" height="90" fill="currentColor" class="bi bi-1-circle" viewBox="0 0 16 16">
  <path d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8Zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0ZM9.283 4.002V12H7.971V5.338h-.065L6.072 6.656V5.385l1.899-1.383h1.312Z"/>
</svg>   
       </div>
   </div> 
   <div class="col-lg-4 ">
       <div class="col-lg-10 offset-lg-1 landing_item landing_thirdColor" style="text-align:center">
           hellooooooooooooooooooooo    
           <svg style = "text-align:center" xmlns="http://www.w3.org/2000/svg" width="90" height="90" fill="currentColor" class="bi bi-1-circle" viewBox="0 0 16 16">
  <path d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8Zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0ZM9.283 4.002V12H7.971V5.338h-.065L6.072 6.656V5.385l1.899-1.383h1.312Z"/>
</svg>   
        </div>
    </div> 


</div>
<div class="landingPageVerticalSeparator"></div>
<div class="row">
    <div class="col-lg-6">
        <p>About us</p>
        <h2>Unique ideas and soluation</h2>
        <p>LLorem ipsum dolor sit amet LLorem ipsum dolor sit amet LLorem ipsum dolor sit amet LLorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet<</p>
        <button>READ MORE</button>
    </div>
    <div class="col-lg-6 landing_posRelative">
        <div class="landing_secondImageMargin"></div>
        <img class="landing_secondRowImage" src="https://imgs.search.brave.com/WylfdlH6YkDiq6ratyqe1R61GlyTThAs3umASd5ALto/rs:fit:1200:1200:1/g:ce/aHR0cHM6Ly9pY2hl/Zi5iYmNpLmNvLnVr/L25ld3MvNjI0L2Nw/c3Byb2RwYi9EMzBF/L3Byb2R1Y3Rpb24v/XzEwNTIwMzA0NV9j/cGkuY2hhcnQtbmMu/cG5n" />
    </div>
</div>

InflationTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InflationTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InflationTracker.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InflationTracker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Groceries" asp-action="Index">Groceries</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - InflationTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Scriptsee", required: false)
</body>
</html>